### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by fingolfin** [JuliaRandom/RandomExtensions.jl#14]
It seems the gh-pages branch only contains the dev documentation, but not docs for a stable release. As a result, the README.md link to https://juliarandom.github.io/RandomExtensions.jl/stable gives a 404 error

**Comment by ViralBShah** [comment]
Fixed in 7d326f2178ed264e265c81ac5b469c281bb8785c

**Comment by fingolfin** [comment]
@rfourquet maybe you can also look into this -- it might be a simple matter of the workflow not having been run here yet or so...

However, it might be a good idea to also verify that `DOCUMENTER_KEY` is set, so that once a release is made, the documentation can be uploaded by the CI job.

**Comment by fingolfin** [comment]
Sorry my comment overlapped with @ViralBShah's action

**Comment by fingolfin** [comment]
I think it would be good to add the stable link back once there was a release

**Comment by rfourquet** [comment]
Yes I assumed initially this link was not working because there had not been a stable release yet since the documentation page was started, but I wil try to fix that.

**Comment by fingolfin** [comment]
sure, no problem

**Comment by fingolfin** [comment]
DOCUMENTER_KEY setup was indeed broken, I've now fixed it.

**Comment by fingolfin** [comment]
This also is relevant for TagBot, so I've now re-run that action to update the website for the release. This took care of creating the missing https://github.com/JuliaRandom/RandomExtensions.jl/releases/tag/v0.4.4 exists and so do https://juliarandom.github.io/RandomExtensions.jl/v0.4/ and https://JuliaRandom.github.io/RandomExtensions.jl/stable
